// gateway/locality-match.mjs — ENCLAVE country resolver for Trusted Locations v2.
// MUST stay BEHAVIORALLY EQUIVALENT to lib/locality-match.ts (a parity test asserts it).
// The enclave can't import lib/country-codes.ts, so the name->ISO-2 base is BAKED here,
// generated from that vendored list. FAIL-OPEN: an unresolved name returns null (the caller
// must never burn on null). Cities are matched verbatim elsewhere; this is countries only.

export function normalizeCountryName(s) {
  return (s ?? "")
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[[^]]*]/g, " ")
    .replace(/[.,()'’]/g, " ")
    .replace(/^s*thes+/, "")
    .replace(/s+/g, " ")
    .trim();
}

// Base name->ISO-2, generated from lib/country-codes.ts (DO NOT hand-edit; regenerate).
const BASE = [
  ["United States", "US"],
  ["United Kingdom", "GB"],
  ["Canada", "CA"],
  ["Australia", "AU"],
  ["Germany", "DE"],
  ["France", "FR"],
  ["India", "IN"],
  ["Brazil", "BR"],
  ["Russia", "RU"],
  ["United Arab Emirates", "AE"],
  ["Afghanistan", "AF"],
  ["Albania", "AL"],
  ["Algeria", "DZ"],
  ["Andorra", "AD"],
  ["Angola", "AO"],
  ["Antigua and Barbuda", "AG"],
  ["Argentina", "AR"],
  ["Armenia", "AM"],
  ["Aruba", "AW"],
  ["Austria", "AT"],
  ["Azerbaijan", "AZ"],
  ["Bahamas", "BS"],
  ["Bahrain", "BH"],
  ["Bangladesh", "BD"],
  ["Barbados", "BB"],
  ["Belarus", "BY"],
  ["Belgium", "BE"],
  ["Belize", "BZ"],
  ["Benin", "BJ"],
  ["Bhutan", "BT"],
  ["Bolivia", "BO"],
  ["Bosnia and Herzegovina", "BA"],
  ["Botswana", "BW"],
  ["Brunei", "BN"],
  ["Bulgaria", "BG"],
  ["Burkina Faso", "BF"],
  ["Burundi", "BI"],
  ["Cambodia", "KH"],
  ["Cameroon", "CM"],
  ["Cape Verde", "CV"],
  ["Central African Republic", "CF"],
  ["Chad", "TD"],
  ["Chile", "CL"],
  ["China", "CN"],
  ["Colombia", "CO"],
  ["Comoros", "KM"],
  ["Congo", "CG"],
  ["Congo (DRC)", "CD"],
  ["Costa Rica", "CR"],
  ["Côte d'Ivoire", "CI"],
  ["Croatia", "HR"],
  ["Cuba", "CU"],
  ["Cyprus", "CY"],
  ["Czech Republic", "CZ"],
  ["Denmark", "DK"],
  ["Djibouti", "DJ"],
  ["Dominica", "DM"],
  ["Dominican Republic", "DO"],
  ["Ecuador", "EC"],
  ["Egypt", "EG"],
  ["El Salvador", "SV"],
  ["Equatorial Guinea", "GQ"],
  ["Eritrea", "ER"],
  ["Estonia", "EE"],
  ["Eswatini", "SZ"],
  ["Ethiopia", "ET"],
  ["Fiji", "FJ"],
  ["Finland", "FI"],
  ["Gabon", "GA"],
  ["Gambia", "GM"],
  ["Georgia", "GE"],
  ["Ghana", "GH"],
  ["Greece", "GR"],
  ["Greenland", "GL"],
  ["Grenada", "GD"],
  ["Guatemala", "GT"],
  ["Guinea", "GN"],
  ["Guinea-Bissau", "GW"],
  ["Guyana", "GY"],
  ["Haiti", "HT"],
  ["Honduras", "HN"],
  ["Hong Kong", "HK"],
  ["Hungary", "HU"],
  ["Iceland", "IS"],
  ["Indonesia", "ID"],
  ["Iran", "IR"],
  ["Iraq", "IQ"],
  ["Ireland", "IE"],
  ["Israel", "IL"],
  ["Italy", "IT"],
  ["Jamaica", "JM"],
  ["Japan", "JP"],
  ["Jordan", "JO"],
  ["Kazakhstan", "KZ"],
  ["Kenya", "KE"],
  ["Kiribati", "KI"],
  ["Kosovo", "XK"],
  ["Kuwait", "KW"],
  ["Kyrgyzstan", "KG"],
  ["Laos", "LA"],
  ["Latvia", "LV"],
  ["Lebanon", "LB"],
  ["Lesotho", "LS"],
  ["Liberia", "LR"],
  ["Libya", "LY"],
  ["Liechtenstein", "LI"],
  ["Lithuania", "LT"],
  ["Luxembourg", "LU"],
  ["Macau", "MO"],
  ["Madagascar", "MG"],
  ["Malawi", "MW"],
  ["Malaysia", "MY"],
  ["Maldives", "MV"],
  ["Mali", "ML"],
  ["Malta", "MT"],
  ["Marshall Islands", "MH"],
  ["Mauritania", "MR"],
  ["Mauritius", "MU"],
  ["Mexico", "MX"],
  ["Micronesia", "FM"],
  ["Moldova", "MD"],
  ["Monaco", "MC"],
  ["Mongolia", "MN"],
  ["Montenegro", "ME"],
  ["Morocco", "MA"],
  ["Mozambique", "MZ"],
  ["Myanmar", "MM"],
  ["Namibia", "NA"],
  ["Nauru", "NR"],
  ["Nepal", "NP"],
  ["Netherlands", "NL"],
  ["New Zealand", "NZ"],
  ["Nicaragua", "NI"],
  ["Niger", "NE"],
  ["Nigeria", "NG"],
  ["North Korea", "KP"],
  ["North Macedonia", "MK"],
  ["Norway", "NO"],
  ["Oman", "OM"],
  ["Pakistan", "PK"],
  ["Palau", "PW"],
  ["Palestine", "PS"],
  ["Panama", "PA"],
  ["Papua New Guinea", "PG"],
  ["Paraguay", "PY"],
  ["Peru", "PE"],
  ["Philippines", "PH"],
  ["Poland", "PL"],
  ["Portugal", "PT"],
  ["Puerto Rico", "PR"],
  ["Qatar", "QA"],
  ["Romania", "RO"],
  ["Rwanda", "RW"],
  ["Saint Kitts and Nevis", "KN"],
  ["Saint Lucia", "LC"],
  ["Saint Vincent and the Grenadines", "VC"],
  ["Samoa", "WS"],
  ["San Marino", "SM"],
  ["São Tomé and Príncipe", "ST"],
  ["Saudi Arabia", "SA"],
  ["Senegal", "SN"],
  ["Serbia", "RS"],
  ["Seychelles", "SC"],
  ["Sierra Leone", "SL"],
  ["Singapore", "SG"],
  ["Slovakia", "SK"],
  ["Slovenia", "SI"],
  ["Solomon Islands", "SB"],
  ["Somalia", "SO"],
  ["South Africa", "ZA"],
  ["South Korea", "KR"],
  ["South Sudan", "SS"],
  ["Spain", "ES"],
  ["Sri Lanka", "LK"],
  ["Sudan", "SD"],
  ["Suriname", "SR"],
  ["Sweden", "SE"],
  ["Switzerland", "CH"],
  ["Syria", "SY"],
  ["Taiwan", "TW"],
  ["Tajikistan", "TJ"],
  ["Tanzania", "TZ"],
  ["Thailand", "TH"],
  ["Timor-Leste", "TL"],
  ["Togo", "TG"],
  ["Tonga", "TO"],
  ["Trinidad and Tobago", "TT"],
  ["Tunisia", "TN"],
  ["Turkey", "TR"],
  ["Turkmenistan", "TM"],
  ["Tuvalu", "TV"],
  ["Uganda", "UG"],
  ["Ukraine", "UA"],
  ["Uruguay", "UY"],
  ["Uzbekistan", "UZ"],
  ["Vanuatu", "VU"],
  ["Vatican City", "VA"],
  ["Venezuela", "VE"],
  ["Vietnam", "VN"],
  ["Yemen", "YE"],
  ["Zambia", "ZM"],
  ["Zimbabwe", "ZW"],
];

// Hand-curated aliases (APPEND-ONLY) — MUST match lib/locality-match.ts ALIAS_ROWS.
const ALIAS_ROWS = [
  ["The Netherlands", "NL"], ["Netherlands", "NL"],
  ["Czechia", "CZ"], ["Czech Republic", "CZ"],
  ["South Korea", "KR"], ["Republic of Korea", "KR"], ["Korea, Republic of", "KR"],
  ["North Korea", "KP"], ["Democratic People's Republic of Korea", "KP"],
  ["Russia", "RU"], ["Russian Federation", "RU"],
  ["Myanmar", "MM"], ["Myanmar [Burma]", "MM"], ["Burma", "MM"],
  ["Ivory Coast", "CI"], ["Côte d'Ivoire", "CI"],
  ["Vietnam", "VN"], ["Viet Nam", "VN"],
  ["Macao", "MO"], ["Macau", "MO"],
  ["Hong Kong", "HK"],
  ["Taiwan", "TW"], ["Taiwan, Province of China", "TW"],
  ["Kosovo", "XK"],
  ["Turkey", "TR"], ["Türkiye", "TR"],
  ["North Macedonia", "MK"], ["Macedonia", "MK"],
  ["Eswatini", "SZ"], ["Swaziland", "SZ"],
  ["Democratic Republic of the Congo", "CD"], ["DR Congo", "CD"], ["Congo, The Democratic Republic of the", "CD"],
  ["Republic of the Congo", "CG"], ["Congo", "CG"],
  ["Republic of Moldova", "MD"], ["Moldova", "MD"],
  ["Palestine", "PS"], ["State of Palestine", "PS"], ["Palestinian Territory", "PS"],
  ["United States", "US"], ["United States of America", "US"], ["USA", "US"],
  ["United Kingdom", "GB"], ["Great Britain", "GB"], ["UK", "GB"],
  ["Vatican City", "VA"], ["Holy See", "VA"], ["Holy See (Vatican City State)", "VA"],
  ["Bolivia", "BO"], ["Plurinational State of Bolivia", "BO"],
  ["Venezuela", "VE"], ["Bolivarian Republic of Venezuela", "VE"],
  ["Tanzania", "TZ"], ["United Republic of Tanzania", "TZ"],
  ["Iran", "IR"], ["Islamic Republic of Iran", "IR"],
  ["Syria", "SY"], ["Syrian Arab Republic", "SY"],
  ["Laos", "LA"], ["Lao People's Democratic Republic", "LA"],
  ["Brunei", "BN"], ["Brunei Darussalam", "BN"],
  ["Micronesia", "FM"], ["Federated States of Micronesia", "FM"],
  ["Cape Verde", "CV"], ["Cabo Verde", "CV"],
];

const NAME_TO_ISO2 = new Map();
for (const [n, i] of BASE) NAME_TO_ISO2.set(normalizeCountryName(n), i.toUpperCase());
for (const [n, i] of ALIAS_ROWS) NAME_TO_ISO2.set(normalizeCountryName(n), i);

export function countryNameToIso2(name) {
  if (!name) return null;
  const norm = normalizeCountryName(name);
  if (!norm) return null;
  return NAME_TO_ISO2.get(norm) ?? null;
}

export function countryOf(locality) {
  if (!locality) return "";
  const i = locality.lastIndexOf(",");
  return (i === -1 ? locality : locality.slice(i + 1)).trim();
}

export function platformClass(platform) {
  return /android|ios|iphone|ipad/i.test(String(platform ?? "")) ? "mobile" : "desktop";
}
